# Site wide configuration

title: Made Mistakes
description: "Personal website of designer slash illustrator Michael Rose."
logo: site-logo.png
teaser: default-teaser.png
locale: en_US
url: http://mademistakes.com


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll/minibundle
include: [".htaccess"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]  


# Site owner
owner:
  name: Michael Rose
  email: michael@mademistakes.com
  twitter: mmistakes
  google:
    ad-client: ca-pub-7328585512091257
    ad-slot: 3049671934
    analytics: UA-2011187-1
    plus: http://plus.google.com/118238196859537351707
    verify: geapSKtvpBNDSfXVmF09E9CnaHGglbO61r4XgLZtEmo
  bing:   
    verify: D81F4C18A6CB3018F64D7C827D953DFD
  alexa:
    verify: Y5DYjZ4VWlrQzBP5kcQJeOKLNas
  bio: "Just another boring, time traveling, designer slash illustrator from Buffalo."
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: mmistakes